import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

function getOpenAI() {
  return new OpenAI({
    baseURL: "https://api.deepseek.com/v1",
    apiKey: process.env.OPENAI_API_KEY,
  });
}

export async function POST(req: NextRequest) {
  try {
    const { subject, gradeLevel, topic, duration, learningStyle, materials } = await req.json();

    const prompt = `You are an expert K-12 educator and instructional designer. Generate a detailed, classroom-ready lesson plan for the following:

**Lesson Details:**
- Subject: ${subject}
- Grade Level: ${gradeLevel}
- Topic: ${topic}
- Duration: ${duration}
- Preferred Learning Style: ${learningStyle}
- Available Materials: ${materials || "Standard classroom materials"}

Please generate a comprehensive lesson plan using the direct instruction model with these sections:

# LESSON PLAN: ${topic}

## 1. LESSON OVERVIEW
| Field | Details |
|-------|---------|
| Subject | ${subject} |
| Grade Level | ${gradeLevel} |
| Topic | ${topic} |
| Duration | ${duration} |
| Learning Style Focus | ${learningStyle} |

## 2. LEARNING OBJECTIVES
Write 3-5 measurable learning objectives using the ABCD format (Audience, Behavior, Condition, Degree):
1. Students will be able to...
2. Students will be able to...
3. Students will be able to...

## 3. STANDARDS ALIGNMENT
List 2-3 relevant academic standards this lesson addresses (e.g., Common Core, NGSS, state standards).

## 4. MATERIALS & RESOURCES
- [ ] Teacher materials (presentations, handouts, etc.)
- [ ] Student materials (worksheets, manipulatives, etc.)
- [ ] Technology resources (if applicable)
- [ ] Optional: advance preparation requirements

## 5. LESSON PROCEDURE

### 🪝 HOOK / ANTICIPATORY SET (5-10% of time)
Creative opening activity to engage students and activate prior knowledge. Include specific questions to ask.

### 📖 INSTRUCTION / DIRECT TEACHING (20-30% of time)
Step-by-step teaching sequence:
1. Step 1: [Description]
2. Step 2: [Description]
3. Step 3: [Description]
Include specific teacher actions, language to use, and things to check for understanding.

### ✋ GUIDED PRACTICE (20-25% of time)
Structured practice activities where teacher and students work together. Include:
- Collaborative tasks
- Scaffolding techniques
- Checking for understanding questions

### 🎯 INDEPENDENT PRACTICE (20-25% of time)
Individual work activities to demonstrate understanding. Include:
- Assigned tasks
- Differentiation options
- Extension activities for advanced learners

### 🧹 CLOSURE / LESSON WRAP-UP (10-15% of time)
- Summary of key takeaways
- Exit ticket prompt
- Preview of next lesson
- Students reflect on their learning

## 6. DIFFERENTIATION STRATEGIES
| Student Need | Strategy |
|-------------|----------|
| Struggling learners | |
| Advanced learners | |
| English Language Learners | |
| Students with IEPs | |

## 7. ASSESSMENT
### Formative Assessment (During Lesson)
- Observation checklist
- Questioning techniques
- Exit tickets

### Summative Assessment (End of Unit)
[Describe end-of-unit assessment aligned with learning objectives]

## 8. CLASSROOM ACTIVITY SHEETS

### Activity 1: [Name]
- **Purpose:** [What skill does this develop?]
- **Instructions:** Step-by-step directions for students
- **Materials needed:** [List]

### Activity 2: [Name]
- **Purpose:** [What skill does this develop?]
- **Instructions:** Step-by-step directions for students
- **Materials needed:** [List]

### Activity 3: [Name]
- **Purpose:** [What skill does this develop?]
- **Instructions:** Step-by-step directions for students
- **Materials needed:** [List]

## 9. HOMEWORK / EXTENSION IDEAS
- Standard homework assignment
- Creative extension projects
- Family involvement activity

## 10. TEACHER NOTES & REFLECTION PROMPTS
- Common misconceptions to watch for
- Tips for first-time delivery
- Reflection questions for after the lesson

---
*This lesson plan was generated by AI. Review and customize before classroom use.*`;

    const openai = getOpenAI();
    const completion = await openai.chat.completions.create({
      model: "deepseek-chat",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
      max_tokens: 4000,
    });

    const content = completion.choices[0]?.message?.content || "No response generated.";
    return NextResponse.json({ result: content });
  } catch (error: unknown) {
    console.error("Error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
